### ISSUE TITLE
Missing a License file

### ISSUE THREAD

**Issue by azemetre** [abhinaba-ghosh/axe-playwright#1]
Hello!

I really enjoy your project, notice that there is a license defined in the `package.json` file but not in the repo itself. Is it possible to add one as well? It helps with compliance scanning tools.

I can open a PR adding the file as well, if you'd like.

Thanks.

**Comment by abhinaba-ghosh** [comment]
Hi @azemetre , Thanks for pointing out the missing pieces. I have added the license file in the latest version.
