### ISSUE TITLE
Update documentation about HTML Report

### ISSUE THREAD

**Issue by torimori-k** [abhinaba-ghosh/axe-playwright#216]
In [HTML Report](https://github.com/abhinaba-ghosh/axe-playwright#html-report) section of the current README.md, it shows
```
await checkA11y(
      page,
      'form',
      {
        axeOptions: {
          runOnly: {
            type: 'tag',
            values: ['wcag2a'],
          },
        },
      },
      true, 'default',
      {
        outputDirPath: 'results',
        outputDir: 'accessibility',
        reportFileName: 'accessibility-audit.html'
      }
    )
```

However, when I tried creating the HTML report based on this example, `'default'` as a value of `reporter` parameter did not work, and this function call did not create a report file. Instead, I had to use `'html'` option for this value.

I am not sure if this code snippet is an actual working example, but it would be great if this can be updated to avoid confusion.

**Comment by abhinaba-ghosh** [comment]
@torimori-k would you mind raising a PR for the same?

**Comment by torimori-k** [comment]
I couldn't link my PR to this issue, so I will leave the link here: https://github.com/abhinaba-ghosh/axe-playwright/pull/220

**Comment by torimori-k** [comment]
https://github.com/abhinaba-ghosh/axe-playwright/pull/220 This change has been merged. Closing this issue.
