### ISSUE TITLE
Not all axe tag-values are supported

### ISSUE THREAD

**Issue by BillyBolton** [abhinaba-ghosh/axe-playwright#28]
The only [axe-core tags](https://github.com/dequelabs/axe-core/blob/ec00dc78a71305bf98e746f489de3e30aa87bfe6/doc/API.md#axe-core-tags) that seem supported are:
- working = ['wcag2a', 'best-practice']
- notWorking = ['wcag2aa', 'wcag21a', 'wcag21aa', 'wcag***', 'ACT', 'section508', 'experimental']'

I need to test up to wcag21aa. Is there a plan to support this in the future?

**Comment by BeataKr** [comment]
Are you sure, because in the report I found vulnerabilities with tags: wcag2a wcag412 wcag244 section508 section508.22.a ACT

**Comment by abhinaba-ghosh** [comment]
Thanks @BeataKr 

@BillyBolton the utility internally using axe-core, so all [guided rules](https://github.com/dequelabs/axe-core/blob/develop/doc/rule-descriptions.md) are supported out of the box.
