### ISSUE TITLE
resultTypes option has no effect

### ISSUE THREAD

**Issue by jrpool** [abhinaba-ghosh/axe-playwright#37]
Using the resultTypes option with getViolations makes no difference. The only array that gets generated is a violations array, even if resultTypes is set to include passes and/or incomplete.

**Comment by ssams** [comment]
just stumbled across this as I also tried to retrieve the "needs review" aka "incomplete" items and didn't see anything in the result array ... `getViolations` currently only returns the `violations` part of the results but not the full structure (https://github.com/abhinaba-ghosh/axe-playwright/blob/cafba4148aecb9ef3f1b24110d28a3765c12f1e8/src/index.ts#L61), hence everything else is left out even when adding it in the options.
