### ISSUE TITLE
Usage with Playwright Test

### ISSUE THREAD

**Issue by Phonesis** [abhinaba-ghosh/axe-playwright#72]
Playwright has recently introduced Playwright Test - which is a test runner and nicer way to use Playwright in general.

I wondered if this lib will work with it? If so, be good to see some documentation / examples?

**Comment by igorfiv** [comment]
I found it very useful for self the next article about how to test accessibility
https://medium.com/@praveenpeiris95/accessibility-testing-using-playwright-694437178ed5

**Comment by abhinaba-ghosh** [comment]
Thanks for sharing the article @igorfiv
