### ISSUE TITLE
Update playwright and axe-core dependencies

### ISSUE THREAD

**Issue by thales-oliveira** [abhinaba-ghosh/axe-playwright#89]
We're currently seeing a compatibility issue when using `axe-playwright` in our project.

The type of the property `runOnly` from `axe-core`'s `RunOptions` has changed on a newer version, causing the following error:

```no-highlight
Types of property 'runOnly' are incompatible.
    Type 'string | RunOnly | string[] | undefined' is not assignable to type 'string[] | RunOnly | undefined'.
      Type 'string' is not assignable to type 'string[] | RunOnly | undefined'.
```

Could you please update both `axe-core` and `playwright` dependencies to their latest versions.

Thanks in advance.

**Comment by abhinaba-ghosh** [comment]
@thales-oliveira can you please raise a PR with the same?
