### ISSUE TITLE
Return type information for getAxeResults is incorrect

### ISSUE THREAD

**Issue by ssams** [abhinaba-ghosh/axe-playwright#90]
Short follow-up to https://github.com/abhinaba-ghosh/axe-playwright/pull/63, the type of the `getAxeResults` function is wrong in the `index.d.ts`:

```diff
diff --git a/node_modules/axe-playwright/index.d.ts b/node_modules/axe-playwright/index.d.ts
index dcbfbd9..24b8fe0 100644
--- a/node_modules/axe-playwright/index.d.ts
+++ b/node_modules/axe-playwright/index.d.ts
@@ -75,7 +75,7 @@ export function configureAxe(page: Page, options?: ConfigOptions): Promise<void>
  * @param context
  * @param options
  */
- export function getAxeResults(page: Page, context?: ElementContext, options?: RunOptions): Promise<AxeResults[]>
+ export function getAxeResults(page: Page, context?: ElementContext, options?: RunOptions): Promise<AxeResults>
 
 /**
  * Runs axe-core tools on the relevant page and returns all accessibility violations detected on the page
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by ssams** [comment]
Also as noted over in the related PR:

> The changes are available on `v1.1.9`
@abhinaba-ghosh 
I just installed 1.1.9 and do not see any of these changes.

_Originally posted by @Basti098765 in https://github.com/abhinaba-ghosh/axe-playwright/issues/63#issuecomment-916742475_

This seems to be still the case, I don't see the addition of `getAxeResults` and other changes in the published packages for *1.1.9*. Code seems to be identical to an older version, just with a new version number? I assume this may be why this error went unnoticed for a while, won't see it when installing via npm.

**Comment by abhinaba-ghosh** [comment]
@ssams good catch! 

Can you try `v1.1.10`?

**Comment by ssams** [comment]
> @ssams good catch!
> 
> Can you try `v1.1.10`?

The release includes the changes in `src` now, but contents of `dist` in the published package are still outdated and do not contain the additions. Hence there's an error at runtime when calling the function (e.g. _"TypeError: (0 , _axePlaywright.getAxeResults) is not a function"_).

I've also setup a PR to fix the type information mentioned in the original issue description.

**Comment by abhinaba-ghosh** [comment]
Let's try `v1.1.11`

**Comment by ssams** [comment]
looks good now, thanks.

I've found another missed export however in the new published version, I'll setup another PR.
