### ISSUE TITLE
Add log level functionality

### ISSUE THREAD

**Issue by yannbf** [abhinaba-ghosh/axe-playwright#95]
Hey, we've been using this lib in our project and that is great! 
However when there are no violations, I'd rather not have any logs. When looking at the results of the tests, there is quite some noise added there. Would it be possible to either remove the log (no error logs should mean success), or add a log level so that these logs only appear when set to "verbose" or something like that?

![image](https://user-images.githubusercontent.com/1671563/162162810-1748a452-3bca-43bb-b2f1-66c9e6ee7510.png)

Thank you!

**Comment by Kosai106** [comment]
@emilbjorklund while this does work, sadly the types for `checkA11y` aren't updated correctly for this. See https://github.com/abhinaba-ghosh/axe-playwright/blob/master/index.d.ts#L58-L63

```ts
export function checkA11y(
  page: Page,
  context?: ElementContext,
  options?: Options,
  skipFailures?: boolean,
  // ... Reporter missing here
): Promise<void>
```
