### ISSUE TITLE
Improved report messages

### ISSUE THREAD

**Issue by yannbf** [abhinaba-ghosh/axe-playwright#96]
As a followup of #95 

One thing I noticed in this library is that there is both a report functionality tied to `assert` and there are a couple console.logs/table happening.

Because the logs are not strictly connected to assert, they will happen at a different time than the assert error message and that might be confusing to users. 

Also, Axe provides a lot of very insightful information that could be covered in the messages coming from this library.

Therefore I'd like to ask what are your thoughts in improving the reports here from:
![image](https://user-images.githubusercontent.com/1671563/162170785-ae5cd669-04ea-4c68-831c-3e7f13cf0d69.png)

To removing all the logs and passing the error message to assert, looking like (very much inspired by the reports from [jest-axe](https://github.com/nickcolley/jest-axe)):
![image](https://user-images.githubusercontent.com/1671563/162170456-669165b9-d4d2-47fe-8bfe-1edaae2e5b85.png)

I'd be happy to put up a PR!

**Comment by jasikpark** [comment]
This would be great to have!
